services:
  api:
    build:
      context: ./api         
      dockerfile: ../docker/Dockerfile.api
    platform: linux/amd64      
    container_name: go-api
    ports:
      - "8080:8080"
    volumes:
      - ./api/data:/app/data
    environment:
      - SQLITE_PATH=/app/data/app.db
  web:
    build:
      context: ./web
      dockerfile: ../docker/Dockerfile.web
    container_name: react-web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app